# The URL the site will be built for
base_url = "127.0.0.1:8080"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "gohugo-theme-ananke"


[params]

twitter = "https://twitter.com/boydjohnson04"
github = "https://github.com/boydjohnson"
featured_image = "img/26131370620_864014805a_o.jpg"
background_color_class = "bg-dark-blue"
body_classes = "avenir bg-washed-blue"
show_reading_time = true
